NumPy in python!!


In [2]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


We can add subtract easily using numpy

In [3]:
print(arr+2)

[3 4 5 6 7]


NumPy array has 3 properties, shape, size, datatype

In [4]:
arr = np.array([10, 20, 30])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Datatype:", arr.dtype)
print("Dimension:",arr.ndim)

Shape: (3,)
Size: 3
Datatype: int64
Dimension: 1


2-D Arrays

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])

print(arr)
print()
print("Dimension:", arr.ndim)
print("Shape:", arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimension: 2
Shape: (3, 3)


This shows 2d array, arr is consist of 2 rows, 3 column so shape is (2, 3)

3D Arrays

In [6]:
arr = np.array([[[1, 2], [3, 4], [11, 22]], [[5, 6], [7, 8], [33, 44]], [[9, 10], [11, 12], [55, 66]]])

print(arr)
print()
print("Dimension:", arr.ndim)
print("Shape:", arr.shape)

[[[ 1  2]
  [ 3  4]
  [11 22]]

 [[ 5  6]
  [ 7  8]
  [33 44]]

 [[ 9 10]
  [11 12]
  [55 66]]]

Dimension: 3
Shape: (3, 3, 2)


That above was definitely not complex lol

Reshaping the arrays

In [7]:
arr = arr.reshape(18)

print(arr)

[ 1  2  3  4 11 22  5  6  7  8 33 44  9 10 11 12 55 66]


arr = np.arange(m) gives an 1D array of m elements 0 to m-1.

In [8]:
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
a = np.array([1, 2, 3])
print(a * 2)

[2 4 6]
